#!/usr/bin/env bash
# zenbuji installer.
#
#   ./install.sh            install CLI + GNOME extension + Nautilus script,
#                           create the venv and install offline backend
#   ./install.sh --light    skip the heavy offline backend (DeepL only)
#   ./install.sh --models   also download the offline translation models
#   ./install.sh --uninstall remove everything except your config
#
# On Bazzite/Silverblue the system Python is immutable, so dependencies live in
# a venv at ~/.local/share/zenbuji/venv. Saved config in ~/.config/zenbuji is
# never touched.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="${XDG_DATA_HOME:-$HOME/.local/share}/zenbuji/venv"
BIN_DIR="$HOME/.local/bin"
EXT_UUID="zenbuji@meeksi39"
EXT_SRC="$REPO_DIR/extension/$EXT_UUID"
EXT_DST="$HOME/.local/share/gnome-shell/extensions/$EXT_UUID"
NAUTILUS_SCRIPTS="$HOME/.local/share/nautilus/scripts"
NAUTILUS_EXT_DIR="$HOME/.local/share/nautilus-python/extensions"

LIGHT=0
WITH_MODELS=0
MODE=install

for arg in "$@"; do
    case "$arg" in
        --light) LIGHT=1 ;;
        --models) WITH_MODELS=1 ;;
        --uninstall) MODE=uninstall ;;
        -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

backup() {
    local target="$1"
    if [[ -e "$target" && ! -L "$target" ]]; then
        local bak="$target.bak.$(date +%s)"
        echo "  backing up existing $target -> $bak"
        mv "$target" "$bak"
    fi
}

link() {
    local src="$1" dst="$2"
    backup "$dst"
    rm -rf "$dst"
    ln -s "$src" "$dst"
    echo "  linked $dst"
}

if [[ "$MODE" == uninstall ]]; then
    echo "Uninstalling zenbuji…"
    rm -f "$BIN_DIR/zenbuji" "$BIN_DIR/zb"
    rm -rf "$EXT_DST"
    rm -f "$NAUTILUS_SCRIPTS/zenbuji (furigana + translation)"
    rm -f "$NAUTILUS_EXT_DIR/zenbuji-nautilus.py"
    # Remove the custom keybinding from the list (leaves other customs intact).
    MK=org.gnome.settings-daemon.plugins.media-keys
    KBPATH=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/zenbuji/
    if command -v gsettings >/dev/null; then
        cur="$(gsettings get $MK custom-keybindings 2>/dev/null || echo "@as []")"
        if [[ "$cur" == *"$KBPATH"* ]]; then
            new="$(printf '%s' "$cur" | sed "s#, *'$KBPATH'##; s#'$KBPATH', *##; s#\['$KBPATH'\]#@as []#")"
            gsettings set $MK custom-keybindings "$new"
            echo "Removed the Super+J custom keybinding."
        fi
    fi
    echo "Removed CLI, extension and Nautilus integration."
    echo "Kept: venv at $VENV (delete by hand to reclaim space),"
    echo "      config at ~/.config/zenbuji."
    echo "Disable the extension with: gnome-extensions disable $EXT_UUID"
    exit 0
fi

echo "Installing zenbuji from $REPO_DIR"

# --- venv + Python deps -------------------------------------------------- #
echo "Setting up venv at $VENV"
mkdir -p "$(dirname "$VENV")"
# --system-site-packages lets the venv use the system PyGObject/GTK (which can't
# be pip-installed on an immutable OS); our pip packages still take precedence.
[[ -d "$VENV" ]] || python3 -m venv --system-site-packages "$VENV"
"$VENV/bin/pip" install -q --upgrade pip wheel
echo "  installing furigana deps (fugashi, unidic-lite, jaconv)…"
"$VENV/bin/pip" install -q fugashi unidic-lite jaconv

if [[ "$LIGHT" -eq 0 ]]; then
    echo "  installing offline translation backend (CPU torch — large)…"
    "$VENV/bin/pip" install -q torch --index-url https://download.pytorch.org/whl/cpu
    "$VENV/bin/pip" install -q argostranslate
else
    echo "  --light: skipping offline backend (configure DeepL with: zenbuji config --deepl-key …)"
fi

# --- CLI launchers ------------------------------------------------------- #
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/zenbuji" <<EOF
#!/usr/bin/env bash
# Generated by zenbuji install.sh — runs the CLI inside its venv.
exec "$VENV/bin/python" "$REPO_DIR/bin/zenbuji.py" "\$@"
EOF
chmod +x "$BIN_DIR/zenbuji"
ln -sf "$BIN_DIR/zenbuji" "$BIN_DIR/zb"
echo "  installed $BIN_DIR/zenbuji (+ zb alias)"

# --- GNOME extension ----------------------------------------------------- #
mkdir -p "$(dirname "$EXT_DST")"
link "$EXT_SRC" "$EXT_DST"
if command -v glib-compile-schemas >/dev/null; then
    glib-compile-schemas "$EXT_SRC/schemas" >/dev/null
    echo "  compiled GSettings schema"
fi

# --- Nautilus integration ------------------------------------------------ #
mkdir -p "$NAUTILUS_SCRIPTS"
SCRIPT_DST="$NAUTILUS_SCRIPTS/zenbuji (furigana + translation)"
cp "$REPO_DIR/nautilus/zenbuji-script.sh" "$SCRIPT_DST"
chmod +x "$SCRIPT_DST"
echo "  installed Nautilus script: right-click ▸ Scripts ▸ zenbuji"

if "$VENV/bin/python" -c "import gi; gi.require_version('Nautilus','4.0')" 2>/dev/null \
   || python3 -c "import gi; gi.require_version('Nautilus','4.0')" 2>/dev/null; then
    mkdir -p "$NAUTILUS_EXT_DIR"
    ln -sf "$REPO_DIR/nautilus/zenbuji-nautilus.py" "$NAUTILUS_EXT_DIR/zenbuji-nautilus.py"
    echo "  installed Nautilus context-menu extension (restart Files to load)"
else
    echo "  (nautilus-python not found — skipping the context-menu extension;"
    echo "   the Scripts entry above works without it)"
fi

# --- Global selection hotkey (GNOME custom keybinding) ------------------- #
# Owned here rather than by the extension so it works immediately (no logout)
# and without the extension enabled.
MK=org.gnome.settings-daemon.plugins.media-keys
KBPATH=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/zenbuji/
if command -v gsettings >/dev/null; then
    cur="$(gsettings get $MK custom-keybindings 2>/dev/null || echo "@as []")"
    if [[ "$cur" != *"custom-keybindings/zenbuji/"* ]]; then
        if [[ "$cur" == "@as []" || "$cur" == "[]" ]]; then
            gsettings set $MK custom-keybindings "['$KBPATH']"
        else
            gsettings set $MK custom-keybindings "${cur%]}, '$KBPATH']"
        fi
    fi
    CK="$MK.custom-keybinding:$KBPATH"
    gsettings set "$CK" name 'zenbuji: look up selection'
    gsettings set "$CK" command "$BIN_DIR/zenbuji popup --selection"
    # Don't clobber a binding the user may have customised.
    existing="$(gsettings get "$CK" binding 2>/dev/null || echo "''")"
    if [[ "$existing" == "''" || "$existing" == "@s ''" ]]; then
        gsettings set "$CK" binding '<Super>j'
    fi
    echo "  bound Super+J → zenbuji popup --selection (GNOME custom shortcut)"
fi

# --- Offline models ------------------------------------------------------ #
if [[ "$WITH_MODELS" -eq 1 && "$LIGHT" -eq 0 ]]; then
    echo "Downloading offline models (ja→en, en→de, …)…"
    "$VENV/bin/python" "$REPO_DIR/bin/zenbuji.py" models --install || true
fi

cat <<EOF

Done.

Next steps:
  • Enable the extension:  gnome-extensions enable $EXT_UUID
    (Wayland: log out and back in first so GNOME loads it.)
  • Offline models:        zenbuji models --install
  • Or use DeepL:          zenbuji config --backend deepl --deepl-key <KEY>
  • Try it:                zenbuji 日本語を勉強しています
  • Hotkey:                Super+J looks up the current selection
EOF
